---
- include: pkg-debian.yml
  when: ansible_os_family == "Debian"

- include: pkg-redhat.yml
  when: ansible_os_family == "RedHat"

- include: agent5.yml
  when: datadog_agent6 == false

- include: agent6.yml
  when: datadog_agent6 == true
